### ISSUE TITLE
Multiple networks aren't deduplicated

### ISSUE THREAD

**Issue by cassidyjames** [elementary/switchboard-plug-networking#102] opened 2018-03-21 17:04 UTC
When near a mesh-type network with multiple physical APs, each AP shows up in the list. Instead, the APs should be deduplicated. GNOME Settings only shows one entry per SSID.

![screenshot from 2018-03-21 11 00 53 2x](https://user-images.githubusercontent.com/611168/37724989-8fae043c-2cf7-11e8-8ab3-36142febe34e.png)

**Comment by tintou** [comment] 2018-03-21 17:04
Duplicate of #97

**Closed by tintou** 2018-03-21 17:04 UTC
